### ISSUE TITLE
Incorrect rendering?

### ISSUE THREAD

**Issue by wjdennen** [tylertate/semantic.gs#19]
Hi, 

Consider this CSS:

``` css

@columns: 12;
@column-width: 60;
@gutter-width: 20;


nav#global {
.column(12);
ul {
    li {
    .column(1);
    text-align: center;
    }
    }
}
```

and this HTML:

``` html
    <nav id="global">
    <ul>
        <li>1</li>
        <li>2</li>
        <li>3</li>
        <li>4</li>
        <li>5</li>
        <li>6</li>
        <li>7</li>
        <li>8</li>
        <li>9</li>
        <li>10</li>
        <li>11</li>
        <li>12</li>
    </ul>
    </nav> 
```

It seems to render incorrectly. I'd expect one row across, but the "12" list item appears on the second row. Perhaps I am misunderstanding how it should work?

Thanks.
