### ISSUE TITLE
Nested Columns (not an issue, just sharing some new code)

### ISSUE THREAD

**Issue by matt-bailey** [tylertate/semantic.gs#62]
Hi Tyler

I've been trying out semantic.gs and it's been a fantastic resource. I've written a modified 'nested' column function which I've found useful and thought I'd share it with you.

It was a while ago I wrote it, but if memory serves me correctly I did it because I didn't find the .push/.pull functions flexible enough, plus I often found that for nested columns I didn't want any margins. You just set the number of columns you want the block to span, the number of columns the parent block spans and a margin width.

There may be an easier way to do this, but for what it's worth here's my code:

``` css
/* Nested blocks - define width as a percentage */

/* default values */
@target-block-width: 0;
@target-block-columns: 3;
@parent-block-columns: 9;
@margin-multiplier: 0;

/* Utility Variables */
@parent-width: @total-width*((((@gutter-width+@column-width)*@parent-block-columns)-@gutter-width) / @gridsystem-width);
@target-block-width: @total-width*((((@gutter-width+@column-width)*@target-block-columns)-@gutter-width) / @gridsystem-width);

@block-width: ((@target-block-width / @parent-width) * 100%);

.nested-block-width(@target-block-columns:@target-block-columns,@parent-block-columns:@parent-block-columns,@margin-multiplier:@margin-multiplier) {
    width: @block-width;
    margin: 0 ((@parent-width*(@gutter-width/@gridsystem-width))*@margin-multiplier);
}

/* Usage */

.nested-block-width(8,12,0); /* target-block-columns, parent-block-columns, margin-multiplier */

```
